include "../common/akka.conf"
include "../common/akka-router.conf"
include "../common/metrics.conf"
include "../common/matsim.conf"
include "seattle.conf"

beam.agentsim.agents.vehicles.linkToGradePercentFilePath = ${beam.inputDirectory}"/r5-fasterrail/r5-residential-partiallysimplified-ferry/linkToGradePercent.csv"
beam.physsim.inputNetworkFilePath = ${beam.inputDirectory}"/r5-fasterrail/r5-residential-partiallysimplified-ferry/physsim-network.xml"


##################################################################
# BEAM ROUTING SERVICE
##################################################################
beam.routing {
  #Base local date in ISO 8061 YYYY-MM-DDTHH:MM:SS+HH:MM
  transitOnStreetNetwork = true
  baseDate = "2023-05-02T00:00:00-07:00"
  r5 {
    directory = ${beam.inputDirectory}"/r5-fasterrail/r5-residential-partiallysimplified-ferry"
    # Departure window in min
    departureWindow = 1.0167
    osmFile = ${beam.inputDirectory}"/r5-fasterrail/r5-residential-partiallysimplified-ferry/seattle-residential-partiallysimplified-ferry-buffer.osm.pbf"
    osmMapdbFile = ${beam.inputDirectory}"/r5-fasterrail/r5-residential-partiallysimplified-ferry/osm.mapdb"
    mNetBuilder.fromCRS = "epsg:4326" # WGS84
    mNetBuilder.toCRS = ${beam.spatial.localCRS}
    linkRadiusMeters = 9000.0
    travelTimeNoiseFraction = 0.05
  }
}