include "../common/akka.conf"
include "../common/akka-router.conf"
include "../common/metrics.conf"
include "../common/matsim.conf"
include "seattle-pilates.conf"

beam.warmStart.initialLinkstatsFilePath = ${beam.inputDirectory}"/r5-fasterrail/seattle-area-cbg412-ferry-network/init.linkstats.csv.gz"
beam.physsim.inputNetworkFilePath = ${beam.inputDirectory}"/r5-fasterrail/seattle-area-cbg412-ferry-network/physsim-network.xml"
beam.warmStart.initialLinkstatsFilePath = ""
beam.routing.r5 {
    directory = ${beam.inputDirectory}"/r5-fasterrail/seattle-area-cbg412-ferry-network"
    osmMapdbFile = ${beam.inputDirectory}"/r5-fasterrail/seattle-area-cbg412-ferry-network/osm.mapdb"
}