include "seattle.conf"

beam.exchange.output.generateSkimsForAllModes = false
beam.agentsim.lastIteration = 2

beam.physsim.name = "JDEQSim"
beam.physsim.flowCapacityFactor = 0.3

beam.agentsim.agents.vehicles.linkToGradePercentFilePath = ""
beam.physsim.inputNetworkFilePath = ${beam.inputDirectory}"/r5/seattle-area-cbg412-ferry-network/physsim-network.xml"
beam.warmStart.initialLinkstatsFilePath = ""
beam.routing.r5 {
    directory = ${beam.inputDirectory}"/r5/seattle-area-cbg412-ferry-network"
    osmMapdbFile = ${beam.inputDirectory}"/r5/seattle-area-cbg412-ferry-network/osm.mapdb"
}