include "seattle.conf"

beam.exchange.output.generateSkimsForAllModes = false
beam.agentsim.lastIteration = 2

beam.physsim.name = "JDEQSim"
beam.physsim.flowCapacityFactor = 0.3

beam.warmStart.type = "linkStatsFromLastRun"
beam.agentsim.agents.vehicles.linkToGradePercentFilePath = ""
beam.warmStart.initialLinkstatsFilePath = ${beam.inputDirectory}"/r5/seattle-area-cbg412-ferry-network/init.linkstats.csv.gz"
beam.physsim.inputNetworkFilePath = ${beam.inputDirectory}"/r5/seattle-area-cbg412-ferry-network/physsim-network.xml"
beam.warmStart.initialLinkstatsFilePath = ""
beam.routing.r5 {
    directory = ${beam.inputDirectory}"/r5/seattle-area-cbg412-ferry-network"
    osmFile = ${beam.inputDirectory}"/r5/seattle-area-cbg412-ferry-network/osm.pbf"
    osmMapdbFile = ${beam.inputDirectory}"/r5/seattle-area-cbg412-ferry-network/osm.mapdb"
}

beam.routing.writeRoutingStatistic = false
beam.agentsim.tuning.transitCapacity = 0.66
