include "../common/akka-router.conf"
include "seattle-base.conf"
include "seattle-base-pilates.conf"
include "seattle-base-pilates-parquet.conf"

beam.agentsim.simulationName = "seattle-freight-20241106-Baseline-0.1FlowCap"

beam.agentsim.agents.freight {
  enabled = true
  plansFilePath = ${beam.inputDirectory}"/freight/2024-11-06/2018_Baseline--snapped-to-cbg412-ferry-network/payloads--2018-Baseline.csv"
  toursFilePath = ${beam.inputDirectory}"/freight/2024-11-06/2018_Baseline--snapped-to-cbg412-ferry-network/tours--2018-Baseline.csv"
  carriersFilePath = ${beam.inputDirectory}"/freight/2024-11-06/2018_Baseline--snapped-to-cbg412-ferry-network/carriers--2018-Baseline.csv"
  vehicleTypesFilePath = ${beam.inputDirectory}"/vehicle-tech/ft-vehicletypes--20241106--2018-Baseline.csv"
  carrierParkingFilePath = ""
  carrierParkingFilePath = ""
  isWgs = true
  generateFixedActivitiesDurations = true
  tourSampleSizeAsFractionOfTotal = 1.0 # FRISM is providing 10% of total population of tours
}

beam.routing.r5.directory = ${beam.inputDirectory}"/r5/seattle-area-cbg412-ferry-network"
beam.routing.r5.osmMapdbFile = ${beam.inputDirectory}"/r5/seattle-area-cbg412-ferry-network/osm.mapdb"
beam.agentsim.agents.vehicles.linkToGradePercentFilePath = ""
beam.physsim.inputNetworkFilePath = ${beam.inputDirectory}"/r5/seattle-area-cbg412-ferry-network/physsim-network.xml"

### CALIBRATION SETUP ###
#beam.warmStart.type = "disabled"
beam.warmStart.type = "linkStatsFromLastRun"
beam.agentsim.agents.vehicles.linkToGradePercentFilePath = ${beam.inputDirectory}"/r5/seattle-area-cbg412-ferry-network/init.linkstats.csv.gz"

beam.agentsim.lastIteration = 3
beam.physsim.name = "JDEQSim"
beam.physsim.relaxation.type = "experiment_2.1"
beam.physsim.relaxation.experiment2_0.internalNumberOfIterations = 3
beam.physsim.relaxation.experiment2_1.fractionOfPopulationToReroute = 0.1
beam.physsim.relaxation.experiment2_0.clearRoutesEveryIteration = true
beam.physsim.relaxation.experiment2_0.clearModesEveryIteration = false
beam.routing.r5.travelTimeNoiseFraction = 0.1

# PhysSim Scaling Params
beam.physsim.flowCapacityFactor = 0.1 #0.135