include "seattle-base.conf"

beam.exchange.output.generateSkimsForAllModes = false
beam.agentsim.lastIteration = 5
beam.routing.writeRoutingStatistic = false
beam.physsim.eventsForFullVersionOfVia = false

beam.inputDirectory = ${PWD}"/input/seattle"
beam.input.simulationPrefix = "year"

beam.exchange.scenario {
  modeMap = [
    "BIKE           -> bike",
    "DRIVEALONEFREE -> car",
    "DRIVEALONEPAY  -> car",
    "DRIVE_COM      -> drive_transit",
    "DRIVE_EXP      -> drive_transit",
    "DRIVE_HVY      -> drive_transit",
    "DRIVE_LOC      -> drive_transit",
    "DRIVE_LRF      -> drive_transit",
    "SHARED2FREE    -> car_hov2",
    "SHARED2PAY     -> car_hov2",
    "SHARED3FREE    -> car_hov3",
    "SHARED3PAY     -> car_hov3",
    "TAXI           -> ride_hail",
    "TNC_SHARED     -> ride_hail_pooled",
    "TNC_SINGLE     -> ride_hail",
    "WALK           -> walk",
    "WALK_COM       -> walk_transit",
    "WALK_EXP       -> walk_transit",
    "WALK_HVY       -> walk_transit",
    "WALK_LOC       -> walk_transit",
    "WALK_LRF       -> walk_transit",
  ]
}
beam.agentsim.taz.parkingFilePath = ""

beam.agentsim.agents.freight.carriersFilePath = ${beam.inputDirectory}"/freight/2025-04-08/2018_Baseline--snapped-to-cbg412-ferry-network/carriers--2018-Baseline.csv"
beam.agentsim.agents.freight.plansFilePath = ${beam.inputDirectory}"/freight/2025-04-08/2018_Baseline--snapped-to-cbg412-ferry-network/payloads--2018-Baseline.csv"
beam.agentsim.agents.freight.toursFilePath = ${beam.inputDirectory}"/freight/2025-04-08/2018_Baseline--snapped-to-cbg412-ferry-network/tours--2018-Baseline.csv"
beam.agentsim.agents.freight.vehicleTypesFilePath = ${beam.inputDirectory}"/vehicle-tech/ft-vehicletypes--20250408--2018-Baseline.csv"
beam.agentsim.agents.modalBehaviors.lccm.filePath = ${beam.inputDirectory}"/lccm-long.csv"
beam.agentsim.agents.modeIncentive.filePath = ${beam.inputDirectory}"/incentives.csv"
beam.agentsim.agents.ptFare.filePath = ${beam.inputDirectory}"/ptFares.csv"
beam.agentsim.agents.vehicles.fuelTypesFilePath = ${beam.inputDirectory}"/samples/beamFuelTypes.csv"
beam.agentsim.agents.vehicles.vehicleTypesFilePath = ${beam.inputDirectory}"/vehicle-tech/vehicleTypes.csv"
beam.agentsim.agents.vehicles.vehiclesFilePath = ${beam.inputDirectory}"/samples/vehicles.csv.gz"
beam.agentsim.taz.filePath = ${beam.inputDirectory}"/shape/block-groups-32048.shp"
beam.agentsim.toll.filePath = ${beam.inputDirectory}"/toll-prices.csv"
beam.calibration.mode.benchmarkFilePath = ${beam.inputDirectory}"/seattle-calibration/benchmark.csv"

beam.agentsim.agents.vehicles.linkToGradePercentFilePath = ""
beam.physsim.inputNetworkFilePath = ${beam.inputDirectory}"/r5/seattle-area-cbg412-ferry-network/physsim-network.xml"
beam.warmStart.initialLinkstatsFilePath = ""
beam.routing.r5 {
    directory = ${beam.inputDirectory}"/r5/seattle-area-cbg412-ferry-network"
    osmMapdbFile = ${beam.inputDirectory}"/r5/seattle-area-cbg412-ferry-network/osm.mapdb"
}


beam.agentsim.agents.vehicles.dummySharedCar.vehicleTypeId = "Car"